/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.0.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    alias(libs.plugins.shadow)
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
    implementation(files("libs/fastcgi-lib.jar"))
    implementation(libs.gson)
    implementation(libs.bundles.prometheus)
}

java {
    // Apply a specific Java toolchain to ease working on different environments.
    toolchain {
        languageVersion = JavaLanguageVersion.of(libs.versions.java.get())
    }
}

application {
    // Define the main class for the application.
    mainClass = "sadnex.web.Main"
}

tasks.jar {
    enabled = false
}

tasks.shadowJar {
    archiveFileName.set("${project.name}.jar")
    manifest {
        attributes["Main-Class"] = application.mainClass
    }
}

tasks.build {
    dependsOn(tasks.shadowJar)
}

tasks.startScripts {
    dependsOn(tasks.shadowJar)
    classpath = files(tasks.shadowJar.get().archiveFile)
}
