[versions]
java = "21"
shadow = "9.1.0"
gson = "2.13.1"
jakarta-web-api = "10.0.0"

[libraries]
gson = { module = "com.google.code.gson:gson", version.ref = "gson"}
jakarta-web-api = { module = "jakarta.platform:jakarta.jakartaee-web-api", version.ref = "jakarta-web-api" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

[bundles]
jakarta = [ "jakarta-web-api" ]